/**
 * OpenAPI → TypeScript client generator (M5, build-time).
 *
 * Emits an ES module for one spec: `export interface <Schema>` per component
 * schema, and `export const api = { <operationId>: (params) => Data.request(...) }`
 * over the paths. The generated client calls @qloom/data's `Data.request` — so
 * the browser payload stays dependency-free.
 *
 * Deliberately covers the controlled subset an Qloom app authors (objects, arrays,
 * $ref, enums, path/query params, JSON request bodies, a 200/201 JSON response).
 * For arbitrary third-party specs, a full generator (openapi-typescript) is the
 * drop-in — see PLAN §10.6.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

function refName(ref: string): string {
  return ref.split("/").pop() ?? "unknown";
}

/** Map a JSON-schema node to a TypeScript type expression. */
function tsType(schema: any): string {
  if (!schema) return "unknown";
  if (schema.$ref) return refName(schema.$ref);
  if (Array.isArray(schema.enum)) return schema.enum.map((v: unknown) => JSON.stringify(v)).join(" | ");
  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return `${tsType(schema.items)}[]`;
    case "object":
    default: {
      const props = schema.properties ?? {};
      const required = new Set<string>(schema.required ?? []);
      const entries = Object.entries(props).map(
        ([k, v]) => `${k}${required.has(k) ? "" : "?"}: ${tsType(v)}`,
      );
      return entries.length ? `{ ${entries.join("; ")} }` : "Record<string, unknown>";
    }
  }
}

const METHODS = ["get", "post", "put", "delete", "patch"] as const;

interface Operation {
  code: string;
}

function generateOperation(path: string, method: string, op: any): Operation {
  const opId: string = op.operationId ?? `${method}${path.replace(/\W+/g, "_")}`;
  const parameters: any[] = op.parameters ?? [];
  const pathParams = parameters.filter((p) => p.in === "path");
  const queryParams = parameters.filter((p) => p.in === "query");
  const bodySchema = op.requestBody?.content?.["application/json"]?.schema;

  const fields: string[] = [];
  for (const p of [...pathParams, ...queryParams]) {
    fields.push(`${p.name}${p.required ? "" : "?"}: ${tsType(p.schema)}`);
  }

  let bodyExpr: string | undefined;
  if (bodySchema) {
    if (bodySchema.properties) {
      const required = new Set<string>(bodySchema.required ?? []);
      const keys = Object.keys(bodySchema.properties);
      for (const k of keys) {
        fields.push(`${k}${required.has(k) ? "" : "?"}: ${tsType(bodySchema.properties[k])}`);
      }
      bodyExpr = `{ ${keys.map((k) => `${k}: params.${k}`).join(", ")} }`;
    } else {
      fields.push(`body: ${tsType(bodySchema)}`);
      bodyExpr = "params.body";
    }
  }

  const paramsType = fields.length ? `{ ${fields.join("; ")} }` : "Record<string, never>";
  const pathExpr =
    "`" + path.replace(/\{(\w+)\}/g, (_m, n) => "${encodeURIComponent(String(params." + n + "))}") + "`";

  const respSchema =
    op.responses?.["200"]?.content?.["application/json"]?.schema ??
    op.responses?.["201"]?.content?.["application/json"]?.schema;
  const returnType = respSchema ? tsType(respSchema) : "void";

  const optsParts: string[] = [];
  if (queryParams.length) {
    optsParts.push(`query: { ${queryParams.map((p) => `${p.name}: params.${p.name}`).join(", ")} }`);
  }
  if (bodyExpr) optsParts.push(`body: ${bodyExpr}`);
  const opts = optsParts.length ? `, { ${optsParts.join(", ")} }` : "";

  return {
    code:
      `  ${opId}: (params: ${paramsType}): Promise<${returnType}> =>\n` +
      `    Data.request<${returnType}>(${JSON.stringify(method.toUpperCase())}, ${pathExpr}${opts}),`,
  };
}

/** Generate the client module source for one OpenAPI spec. */
export function generateApiClient(spec: any): string {
  const schemas = spec.components?.schemas ?? {};
  const schemaLines = Object.entries(schemas).map(
    ([name, schema]) => `export interface ${name} ${tsType(schema)}`,
  );

  const operations: string[] = [];
  for (const [path, item] of Object.entries<any>(spec.paths ?? {})) {
    for (const method of METHODS) {
      if (item[method]) operations.push(generateOperation(path, method, item[method]).code);
    }
  }

  return [
    `// Generated by Qloom from an OpenAPI spec — do not edit, not committed.`,
    `import { Data } from "@qloom/data";`,
    ``,
    ...schemaLines,
    ``,
    `export const api = {`,
    ...operations,
    `};`,
    ``,
  ].join("\n");
}
